module.exports = {
  pil: {
    taskType: 'PIL application',
    identifier: 'Applicant name',
    'new': 'New',
    'autoresolved': 'Draft',
    // 'resubmitted': '',
    'returned-to-applicant': 'Returned',
    'withdrawn-by-applicant': 'Withdrawn',
    'with-ntco': 'Awaiting endorsement',
    // ,
    // 'ntco-endorsed': '',
    'with-licensing': 'Awaiting review',
    // 'with-inspectorate': '',
    'referred-to-inspector': 'Awaiting recommendation',
    'inspector-recommended': 'Recommendation made',
    'inspector-rejected': 'Recommendation made',
    'resolved': 'Granted',
    'rejected': 'Rejected'
  },
  ppl: {
    taskType: 'PIL application',
    identifier: 'Applicant name',
    'new': 'New',
    'autoresolved': 'Draft',
    // 'resubmitted': '',
    'returned-to-applicant': 'Returned',
    'withdrawn-by-applicant': 'Withdrawn',
    'with-ntco': 'Awaiting endorsement',
    // ,
    // 'ntco-endorsed': '',
    'with-licensing': 'Awaiting review',
    // 'with-inspectorate': '',
    'referred-to-inspector': 'Awaiting recommendation',
    'inspector-recommended': 'Recommendation made',
    'inspector-rejected': 'Recommendation made',
    'resolved': 'Granted',
    'rejected': 'Rejected'
  }
};
